export { default as Blog } from './Blog';
export { default as Features } from './Features/Features';
export { default as Features2 } from './Features2/Features2';
export { default as Footer } from './Footer/Footer';
export { default as Header } from './Header/Header';
export { default as Home } from './Home/Home';
export { default as Possibility } from './Possibility';
export { default as WhatGPT3 } from './WhatGPT3';
export { default as Background } from './Background/Background';