// USERS ACTIONS
export const CHANGE_THEME = 'CHANGE_THEME';
export const GET_USER = 'GET_USER';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const SIGN_UP = 'SIGN_UP';
export const SEND_EMAIL = 'SEND_EMAIL';
export const CLEAN_SEND_EMAIL = 'CLEAN_SEND_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE';
export const SIGN_IN_GITHUB = 'SIGN_IN_GITHUB';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const CLEAN_LOG_IN_ERROR = 'CLEAN_LOG_IN_ERROR';
export const UPDATE_DATA_USER = 'UPDATE_DATA_USER';
export const LOAD_STORAGE = 'LOAD_STORAGE';

// PROJECTS ACTIONS
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const GET_ALL_TECHS = 'GET_ALL_TECHS';
export const CREATE_PROJECTS = 'CREATE_PROJECTS';
export const SELECTPAG = 'SELECTPAG';
export const GET_PROJECTS_BY_USER = 'GET_PROJECTS_BY_USER';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const CLEAR_DATA_PROJECTS = 'CLEAR_DATA_PROJECTS';
export const ERROS_PROJECTS = 'ERROS_PROJECTS';
export const NEW_COLLABORATE = 'NEW_COLLABORATE';
export const ERROS_COLLABORATE = 'ERROS_COLLABORATE';
export const GET_PROYECT_COLLABORATION_BY_USER = 'GET_PROYECT_COLLABORATION_BY_USER';
export const LOADING_DATA = 'LOADING_DATA';

// MODAL ADD IMAGE
export const SHOW_MODAL_ADD_IMAGE = 'SHOW_MODAL_ADD_IMAGE';
export const CLOSE_MODAL_ADD_IMAGE = 'CLOSE_MODAL_ADD_IMAGE';

// FILTER PROJECTS ACTIONS
export const FILTER_PROJECTS = 'FILTER_PROJECTS';
export const UPDATE_STATUS_FILTER = 'UPDATE_STATUS_FILTER';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';

// GENERAL ACTIONS
export const OPEN_MESSSAGE_MUST_LOGIN = 'OPEN_MESSSAGE_MUST_LOGIN';
export const CLOSE_MESSSAGE_MUST_LOGIN = 'CLOSE_MESSSAGE_MUST_LOGIN';
export const OPEN_MODAL_INFO_COLLABORATOR = 'OPEN_MODAL_INFO_COLLABORATOR';
export const CLOSE_MODAL_INFO_COLLABORATOR = 'CLOSE_MODAL_INFO_COLLABORATOR';

// BASE URL
export const BASE_URL_FRONT = 'http://localhost:3000';
export const CLOUDINARY = 'https://api.cloudinary.com/v1_1/techmarket/image/upload';
// export const CLOUDINARY = 'https://api.cloudinary.com/v1_1/djgghmpgh/image/upload';