version: "3"

services:
  web:
    container_name: web
    image: node
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo/notesdb
      - PORT=4000
  mongo:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
